spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  environment: test
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    database: H2
    properties:
      ddl-auto: create
      hibernate:
        format-sql: true
        open-in-view: false
    platform: h2
    show-sql: false
  sql:
    init:
      platform: h2